### PR TITLE
Add Noto Sans SC/TC/JP/KR and Noto Serif [CJK] SC/TC/JP/KR

### PR DESCRIPTION
**Pull request by ftake**
Add Noto Sans SC/TC/JP/KR and Noto Serif [CJK] SC/TC/JP/KR to 59-family-prefer-lang-specific.conf

This is minimal fix for Sans alias under environment with Noto Sans SC/TC/JP/KR.

### CODE REVIEW

**Comment by ftake** [comment]
@marguerite This repository is still in use? If not, I will ask to remove this.

**Comment by ftake** [comment]
I mean this repository.

**Comment by marguerite** [comment]
@ftake there’s an error in the zh-hk part, it should be TC not SC.

**Comment by marguerite** [comment]
another pull request was merged.

**Pull request closed without merging**
